### ISSUE TITLE
Doesn't appear to work with ProPresenter 7.7.1

### ISSUE THREAD

**Issue by jayakaran** [greyshirtguy/Pro7LooksHelper-AppleScript#1]
The script doesn't work with ProPresenter 7.7.1

**Comment by greyshirtguy** [comment]
I'll look into this..
Does it work with previous versions of Pro7 for you?
Which MacOS version are you on?

**Comment by jayakaran** [comment]
I only discovered the script last week. I’m using Maverick. The app launches but all I see is the word live in a menu. Clicking on it doesn’t show anything.

**Comment by greyshirtguy** [comment]
Can you check the Accessibility section for the list of app that are permitted to control your computer...
Pro7LooksHelper needs to be in that list..
If it's already there, delete it and drag it back in....(then try re-launching)
![image](https://user-images.githubusercontent.com/1886513/145360348-14727bec-61c7-4d76-8dca-a92e08bbb0cb.png)

**Comment by jayakaran** [comment]
I went ahead and recompiled the code and followed the steps and it works now! Thank you!

**Comment by greyshirtguy** [comment]
There is a new API - I'll be able to create a new version of this app that does NOT need permission to control your computer....
New API is in flux until about Q1 2022 - then I'll make this app again using that...
